//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorTimeSlotTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorTimeSlotTable()
        {
            this.DoctorAppointTables = new HashSet<DoctorAppointTable>();
        }
    
        public int DoctorTimeSlotID { get; set; }
        public int DoctorID { get; set; }
        public string Name { get; set; }
        public System.TimeSpan ToTime { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorAppointTable> DoctorAppointTables { get; set; }
        public virtual DoctorTable DoctorTable { get; set; }
    }
}
