//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class LabTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabTable()
        {
            this.LabAppointTables = new HashSet<LabAppointTable>();
            this.LabTestDetailsTables = new HashSet<LabTestDetailsTable>();
            this.LabTestTables = new HashSet<LabTestTable>();
            this.LabTimeSlotTables = new HashSet<LabTimeSlotTable>();
        }
    
        public int LabID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }


        [Required(ErrorMessage = "*Required!")]

        public string ContactNo { get; set; }

        [Required(ErrorMessage = "*Required!")]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNo { get; set; }

        [Required(ErrorMessage = "*Required!")]
        [DataType(DataType.EmailAddress)]
        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "*Required!")]

        public string PermanentAddress { get; set; }
        public string AboutLab { get; set; }
        public int AccountTypeID { get; set; }
        public string AccountNo { get; set; }
        [NotMapped]
        public HttpPostedFileBase LogFile { get; set; }
        
        public virtual AccountTypeTable AccountTypeTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabAppointTable> LabAppointTables { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabTestDetailsTable> LabTestDetailsTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabTestTable> LabTestTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabTimeSlotTable> LabTimeSlotTables { get; set; }
    }
}
