//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LabTimeSlotTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabTimeSlotTable()
        {
            this.LabAppointTables = new HashSet<LabAppointTable>();
        }
    
        public int LabTimeSlotID { get; set; }
        [Required(ErrorMessage ="*Required!")]
        public int LabID { get; set; }
        [Required(ErrorMessage = "*Required!")]

        public string Name { get; set; }
        [Required(ErrorMessage = "*Required!")]
        [DataType(DataType.Time)]
        public System.TimeSpan ToTime { get; set; }
        [Required(ErrorMessage = "*Required!")]
        [DataType(DataType.Time)]
        public System.TimeSpan FromTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabAppointTable> LabAppointTables { get; set; }
        public virtual LabTable LabTable { get; set; }
    }
}
