//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PatientTestDetailTable
    {
        public int LabAppointDetailID { get; set; }
        [Required(ErrorMessage ="*Required!")]
        public int LabAppointID { get; set; }
        [Required(ErrorMessage = "*Required!")]

        public int LabTestDetailID { get; set; }
        [Required(ErrorMessage = "*Required!")]

        public int PatientValue { get; set; }
    
        public virtual LabAppointTable LabAppointTable { get; set; }
        public virtual LabTestDetailsTable LabTestDetailsTable { get; set; }
    }
}
